### ISSUE TITLE
erleans:get_grain/2 misbehaves if grain module was not loaded

### ISSUE THREAD

**Issue by Licenser** [GOFactory/erleans#13]
When the grain module was not loaded before `erleans:get_grain/2` is called the return value is giving false results (probably due to checking for exported values).

```
3> Grain1 = erleans:get_grain(howl_grain, <<"grain1">>).
#{id => <<"grain1">>,
  implementing_module => howl_grain,
  placement => random}
4> howl_grain:module_info().
5> f().
6> Grain1 = erleans:get_grain(howl_grain, <<"grain1">>).
#{id => <<"grain1">>,
  implementing_module => howl_grain,
  placement => prefer_local,
  provider => ets_provider}
```

**Comment by tsloughter** [comment]
This one I don't think there is a solution for, except patching OTP. It wouldn't be an issue when running a release, since it would be run in `embedded` mode. In tests I've simply manually loaded the modules for grains before the test runs.

`erlang:function_exported` doesn't throw an exception if the module isn't loaded, it simply returns `false`.

**Comment by Licenser** [comment]
Could could the init call module_info() and use the returned exports instead of calling is_exported?
